version: '3'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra
    networks:
      - cassandra-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=minh123
      - GF_SECURITY_ADMIN_USER=minh
    depends_on:
      - cassandra
    networks:
      - cassandra-network

networks:
  cassandra-network:
    driver: bridge
